services:
  # bot:
  #   build: .
  #   command: python3 -u bot.py
  #   volumes:
  #     - .:/bot
  admin:
    build:
      context: ./adminpanel
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .docker_env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_USER=${DB_USER}
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
